# https://golangci-lint.run/usage/configuration/

linters:
  enable-all: true
  disable:
    - ifshort
    - exhaustivestruct
    - golint
    - nosnakecase
    - scopelint
    - varcheck
    - structcheck
    - interfacer
    - maligned
    - deadcode
    - dogsled
    - wrapcheck
    - wastedassign
    - varnamelen
    - testpackage
    - thelper
    - nilerr
    - sqlclosecheck
    - paralleltest
    - nonamedreturns
    - nlreturn
    - nakedret
    - ireturn
    - interfacebloat
    - gosmopolitan
    - gomnd
    - goerr113
    - gochecknoglobals
    - exhaustruct
    - errorlint
    - depguard
    - exhaustive
    - containedctx
    - wsl
    - cyclop
    - dupword
    - errchkjson
    - contextcheck
    - tagalign
    - dupl
    - forbidigo
    - funlen
    - goconst
    - godox
    - gosec
    - lll
    - nestif
    - revive
    - unparam
    - stylecheck
    - gocritic
    - gofumpt
    - gomoddirectives
    - godot
    - gofmt
    - gocognit
    - mirror
    - gocyclo
    - gochecknoinits
    - gci
    - maintidx
    - prealloc
    - goimports
    - errname
    - musttag
    - forcetypeassert
    - whitespace
    - noctx
    - reassign